### PR TITLE
Add wrapper code and compilation instructions

### PR DESCRIPTION
**Pull request by yashsriv**
# Wrapper

A statically compiled binary which can capture the output of any command.  
This file would be used as a wrapper around the commands for system/code based questions.  
Statically compiled so that it works even on busybox.
The exact working of the wrapper is described below :

```
./wrapper arg1 arg2 arg3
```

`arg1` -> file containing commands to be run, while checking the output of only the last command against contents of file `arg2`  
`arg2` -> file to match the output with  
`arg3` -> file to dump outputs of ALL commands in file `arg1`  

Exit code: `0` if `arg2` file content matches, `1` otherwise.
## Compiling

`wrapper.cpp` can be statically compiled using:

```
g++ wrapper.cpp -o wrapper -std=c++11 -static -static-libgcc -static-libstdc++ -I libs
```

Compilation requires the standard `pstreams` [library](http://pstreams.sourceforge.net/) which is available in most major distros - ubuntu, arch  
and is also included in the `libs` folder.

Doesn't matter since we are statically compiling.
## Illegal commands and failures

Due to current limitations, `arg1` should contain only valid `/bin/sh` commands such as:

```
$ cat a.txt | ./a.out
```

instead of 

```
$ ./a.out < cat a.txt
```

Also, currently the checking is not as per CodeChef - (timeout, white space checking).  
They can be implemented easily as and when required.

Pool:

```
 __  __                 _   _
|  \/  | __ _ _ __ __ _| |_| |__   __ _ ___
| |\/| |/ _` | '__/ _` | __| '_ \ / _` / __|
| |  | | (_| | | | (_| | |_| | | | (_| \__ \
|_|  |_|\__,_|_|  \__,_|\__|_| |_|\__,_|___/

```

### CODE REVIEW

**Comment by yashsriv** [comment]
I also have another alternative to appending `2>&1`(just in case another command in `arg1` requires redirection). In that case, the errors and output would be read independently for each individual command and then I can append them together if that's what you need.... I beleive that's better code and I will update this by tonight

**Comment by yashsriv** [comment]
Tried to fix the bugs mentioned in IRC.

Also made the code more elegant and satisfy [Google C++ Guidelines](https://google.github.io/styleguide/cppguide.html) as far as possible.

The guidelines compatibility can be checked using [cpplint.py](https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py) on the file.

**Comment by yashsriv** [comment]
CodeChef style output comparison done. Now only timeout checking is left for which I have the logic ready. Just need to know the requirements

**Comment by yashsriv** [comment]
Also added `zsh` style % after each command and handling for the case when the lastcommand also occurs somewhere in between

**Comment by kunalkap** [comment]
Marathas are awarded 140 points (-10 for mixed stderr and stdout in a single command) for completing this task.

**Pull request merged**
